import { ImageRightsHolderDetail } from "@/types/api/imageRights";

export const rightsHoldersMock: ImageRightsHolderDetail[] = [
  {
    id: "rh-001",
    firstName: "Aïssatou",
    lastName: "Traoré",
    email: "aissatou.traore@example.com",
    phone: "+229 91 22 33 11",
    role: "Actrice principale",
    scope: "Portrait, bande-annonce, affiches urbaines",
    sharePercentage: 22,
    films: 3,
    series: 1,
    status: "actif",
    lastUpdate: "2024-09-12",
    avatar: "/gildas.png",
    startedAt: "2023-10-01",
    expiresAt: "2026-12-31",
    legalMentions: "Contrat d'exploitation d'image pour toutes diffusions SaFLIX (territoires: Afrique, Europe).",
    notes: "Prévenir 30 jours avant toute campagne internationale. Préfère validation des visuels avant diffusion.",
    linkedContents: [
      {
        id: "film-102",
        title: "Au fil du temps",
        type: "film",
        role: "Personnage principal",
        usageScope: "Affiche + bande-annonce",
        period: "2024-2026",
        poster: "/elegbara.png",
        status: "Publié",
      },
      {
        id: "film-205",
        title: "La Rive",
        type: "film",
        role: "Portrait promo",
        usageScope: "Affiches urbaines",
        period: "2024-2025",
        poster: "/r.png",
        status: "Pause",
      },
      {
        id: "serie-044",
        title: "Frontière Nord",
        type: "serie",
        role: "Actrice principale",
        usageScope: "Saisons 1-2",
        period: "2024-2025",
        poster: "/sidebar.jpg",
        status: "Tournage",
      },
    ],
    documents: [
      { label: "Cession de droit image", date: "2023-09-20", type: "Contrat signé" },
      { label: "Consentement RGPD", date: "2023-09-20", type: "Document légal" },
    ],
  },
  {
    id: "rh-002",
    firstName: "Ibrahim",
    lastName: "Soglo",
    email: "ibrahim.soglo@example.com",
    phone: "+229 67 88 90 12",
    role: "Second rôle / figurant premium",
    scope: "Portrait, extraits behind-the-scenes",
    sharePercentage: 8,
    films: 1,
    series: 2,
    status: "en attente",
    lastUpdate: "2024-08-03",
    avatar: "/diamond.png",
    startedAt: "2024-02-15",
    expiresAt: "2025-06-30",
    legalMentions: "Usage limité aux canaux numériques SaFLIX et réseaux sociaux propriétaires.",
    notes: "En attente de validation pour campagne d'affichage physique.",
    linkedContents: [
      {
        id: "film-310",
        title: "Marées Basses",
        type: "film",
        role: "Second rôle",
        usageScope: "Réseaux sociaux + vignette catalogue",
        period: "2024-2025",
        poster: "/file.svg",
        status: "Post-prod",
      },
      {
        id: "serie-131",
        title: "Quartier Lumière",
        type: "serie",
        role: "Cameo",
        usageScope: "Teasers saison 2",
        period: "2024",
        poster: "/window.svg",
        status: "Publié",
      },
      {
        id: "serie-206",
        title: "Oasis",
        type: "serie",
        role: "Personnage récurrent",
        usageScope: "Affiche streaming + stories",
        period: "2024-2026",
        poster: "/bg_stat_card.png",
        status: "En écriture",
      },
    ],
    documents: [
      { label: "Contrat image - édition numérique", date: "2024-02-10", type: "Contrat signé" },
    ],
  },
  {
    id: "rh-003",
    firstName: "Léa",
    lastName: "Mensah",
    email: "lea.mensah@example.com",
    phone: "+33 6 77 12 88 55",
    role: "Réalisatrice / voix-off",
    scope: "Portrait pro + making-of",
    sharePercentage: 15,
    films: 2,
    series: 0,
    status: "expiré",
    lastUpdate: "2024-06-18",
    avatar: "/barcode.png",
    startedAt: "2022-05-01",
    expiresAt: "2024-05-01",
    legalMentions: "Autorisation expirée, renouvellement requis avant toute nouvelle diffusion.",
    notes: "Prévoir renégociation pour l'exploitation des making-of.",
    linkedContents: [
      {
        id: "film-411",
        title: "Les Racines",
        type: "film",
        role: "Narration",
        usageScope: "Teasers voix-off",
        period: "2022-2024",
        poster: "/shape.png",
        status: "Expiré",
      },
      {
        id: "film-523",
        title: "Traversees",
        type: "film",
        role: "Réalisatrice",
        usageScope: "Affiche festival",
        period: "2023-2024",
        poster: "/tax.png",
        status: "Festival",
      },
    ],
    documents: [
      { label: "Cession voix-off", date: "2022-04-20", type: "Contrat expiré" },
    ],
  },
];
